services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mediadreams\MdSaml\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

# EventListeners

  Mediadreams\MdSaml\EventListener\SamlBeforeUserLogoutEventListener:
    tags:
      - name: event.listener
        identifier: 'md-saml/SamlBeforeUserLogoutEventListener'

  Mediadreams\MdSaml\EventListener\SamlAfterUserLoggedOutEventListener:
    tags:
      - name: event.listener
        identifier: 'md-saml/SamlAfterUserLoggedOutEventListener'
