name: TYPO3 Extension TER Release

on:
  push:
    tags:
      - '*'

jobs:
  release-ter:
    name: TYPO3 TER release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to TER
        env:
          TYPO3_API_TOKEN: ${{secrets.TYPO3_API_TOKEN}}
          TAG: ${{env.GITHUB_REF_NAME}}
        run: composer deploy:ter
